#!/bin/bash
cat > $1 <<EOF
const mongoose = require("mongoose");
const path     = require("path");
const fs       = require("fs");
const mp       = path.join(__dirname, "../models");

mongoose.connect("mongodb://localhost/$2");
mongoose.Promise = global.Promise;

fs.readdirSync(mp).forEach(function(file) {
    if(file.indexOf(".js") >= 0) {
        require(mp + "/" + file);
    }
});
EOF
